server:
  port: 8080

spring:
  application:
    name: snappe-backend
  datasource:
    url: jdbc:mysql://localhost:3306/snappe_leads
    username: root
    password: Deep@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    problemdetails:
      enabled: true

app:
  cors:
    allowed-origin: http://localhost:4200